### ISSUE TITLE
More details are expected

### ISSUE THREAD

**Issue by sudalvxin** [koutilya-pnvr/SharinGAN#2]
Thanks for your contribution to this topic. Could you provide more details over your code. For example, the version of Pytorch, or a basic sample run using default parameters.

**Comment by koutilya-pnvr** [comment]
Thanks for your interest. I will update the repo soon with more details. Please be on the lookout. Appreciate your patience.

**Comment by sudalvxin** [comment]
Hi, I am waiting your update. Thanks. : )

**Comment by koutilya-pnvr** [comment]
I added the enviroment.yml file to the repo and also updated the README with "Requirements"
