### ISSUE TITLE
Looking for trained SharinGAN depth estimation model [KITTI]

### ISSUE THREAD

**Issue by Akhil-Gurram** [koutilya-pnvr/SharinGAN#4]
Hi Koutilya, 

Thanks for your contribution to this topic.

With the current script published in Git repo, we notice several bugs, and majorly for reproducing the paper results the important details are missing. [as mentioned in #2 also] 

Can you please update us when the trained Sharingan models and/or the bug-free scripts will be available? 

Thank you,

**Comment by koutilya-pnvr** [comment]
The saved model is made available now. The link is in Readme. We are working on more generic training and validation scripts.
